log_dir: './logs'
decoder: lidar
dataset: ncd

criteria:
  sdf_weight: 10000.0
  fs_weight: 1
  eiko_weight: 1.0
  sdf_truncation: 0.30

decoder_specs:
  depth: 2
  width: 256
  in_dim: 16
  skips: []
  embedder: none
  multires: 0

tracker_specs:
  N_rays: 2048
  learning_rate: 0.04
  step_size: 0.1
  max_voxel_hit: 20
  num_iterations: 30

mapper_specs:
  N_rays_each: 2048
  use_local_coord: False
  voxel_size: 0.2
  step_size: 0.2
  window_size: 5
  num_iterations: 15
  max_voxel_hit: 20
  final_iter: True
  mesh_res: 2
  learning_rate_emb: 0.002
  learning_rate_decorder: 0.005
  learning_rate_pose: 0.001
  freeze_frame: 20
  keyframe_gap: 8
  remove_back: False
  key_distance: 20

debug_args:
  verbose: False
  mesh_freq: 500
