base_config: configs/maicity/maicity.yaml

exp_name: maicity/sqeuence00



data_specs:
  data_path: '/home/evsjtu2/disk1/dengjunyuan/maicity/bin/sequences/00'
  use_gt: False
  max_depth: 50.0
  min_depth: 1.5

tracker_specs:
  start_frame: 0
  end_frame: 699
  read_offset: 1